# Data stats

In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from sdss.metadata import MetaData
from anomaly.utils import specobjid_to_idx

meta = MetaData()

# Custom functions

# Directories

In [2]:
thesis_dir = "/home/elom/gdrive/career/portfolio/phd/thesis_phd"
ch_3_dir = f"{thesis_dir}/chapters/03_figures"

data_dir = "/home/elom/phd/code_phd/spectra"
bin_id = "bin_03"

# Data ingestion

In [3]:
wave = np.load(f"{data_dir}/wave_spectra_imputed.npy")
# convert from Angstroms to nanometers
wave = wave / 10.0

spectra = np.load(
    f"{data_dir}/spectra_imputed.npy",
    mmap_mode="r"
)

In [4]:
drop_meta_data_df = pd.read_csv(
    f"{data_dir}/drop_0_01_z_0_5_4_0_snr_inf.csv.gz",
    index_col="specobjid",
)

In [5]:
drop_meta_data_df.columns

Index(['mjd', 'plate', 'fiberid', 'run2d', 'ra', 'dec', 'z', 'zErr',
       'zWarning', 'class', 'subClass', 'z_noqso', 'zErr_noqso',
       'zWarning_noqso', 'targetType', 'programname', 'instrument', 'snMedian',
       'ABSSB', 'BROAD', 'ebv'],
      dtype='object')

# Overall stats

## z and S/N

In [6]:
drop_meta_data_df[['z', 'snMedian']].describe()

                   z       snMedian
count  728133.000000  728133.000000
mean        0.111624      14.680074
std         0.055983       7.040675
min         0.010000       4.000447
25%         0.070344       9.941171
50%         0.104699      13.152080
75%         0.145940      17.548260
max         0.298085      98.104000

## SDSS classification

In [7]:
drop_meta_data_df.subClass.value_counts(dropna=False).to_clipboard()
drop_meta_data_df.subClass.value_counts(dropna=False)

subClass
NaN                      423053
STARFORMING              223367
STARBURST                 53842
AGN                       15165
BROADLINE                  9737
AGN BROADLINE              1894
STARFORMING BROADLINE       990
STARBURST BROADLINE          85
Name: count, dtype: int64

# Bin 00

## Data

In [8]:
bin_id = 'bin_00'
idx_id_bin_00 = np.load(
    f"{data_dir}/202511_bins/"
    f"{bin_id}/{bin_id}_index_specobjid.npy"
)

bin_00_df = drop_meta_data_df.loc[idx_id_bin_00[:, 1]].copy()

## z and S/N

In [9]:
bin_00_df[['z', 'snMedian']].describe()

                   z       snMedian
count  182033.000000  182033.000000
mean        0.128530       7.823832
std         0.068587       1.478418
min         0.010000       4.000447
25%         0.073498       6.803094
50%         0.120312       8.072596
75%         0.177228       9.062079
max         0.298085       9.941168

## SDSS classification

In [13]:
bin_00_class = bin_00_df.subClass.value_counts(dropna=False)
bin_00_class

subClass
NaN                      88672
STARFORMING              73255
STARBURST                18155
AGN                       1647
BROADLINE                  134
AGN BROADLINE               87
STARFORMING BROADLINE       62
STARBURST BROADLINE         21
Name: count, dtype: int64

# Bin 01

## Data

In [14]:
bin_id = 'bin_01'
idx_id_bin_01 = np.load(
    f"{data_dir}/202511_bins/"
    f"{bin_id}/{bin_id}_index_specobjid.npy"
)

bin_01_df = drop_meta_data_df.loc[idx_id_bin_01[:, 1]].copy()

## z and S/N

In [15]:
bin_01_df[['z', 'snMedian']].describe()

                   z       snMedian
count  182033.000000  182033.000000
mean        0.126529      11.546283
std         0.054148       0.916882
min         0.010006       9.941171
25%         0.085027      10.759940
50%         0.125166      11.544310
75%         0.163471      12.333830
max         0.297165      13.152070

## SDSS class

In [16]:
bin_01_class = bin_01_df.subClass.value_counts(dropna=False)
bin_01_class

subClass
NaN                      104200
STARFORMING               60906
STARBURST                 13200
AGN                        2962
BROADLINE                   395
AGN BROADLINE               214
STARFORMING BROADLINE       134
STARBURST BROADLINE          22
Name: count, dtype: int64

# Bin 02

## Data

In [17]:
bin_id = 'bin_02'
idx_id_bin_02 = np.load(
    f"{data_dir}/202511_bins/"
    f"{bin_id}/{bin_id}_index_specobjid.npy"
)

bin_02_df = drop_meta_data_df.loc[idx_id_bin_02[:, 1]].copy()

## z and S/N

In [18]:
bin_02_df[['z', 'snMedian']].describe()

                   z       snMedian
count  182033.000000  182033.000000
mean        0.111274      15.121389
std         0.045029       1.249269
min         0.010000      13.152080
25%         0.078488      14.031970
50%         0.109936      15.014940
75%         0.140784      16.151210
max         0.297462      17.548210

## SDSS class

In [19]:
bin_02_class = bin_02_df.subClass.value_counts(dropna=False)
bin_02_class

subClass
NaN                      113403
STARFORMING               50770
STARBURST                 12267
AGN                        4083
BROADLINE                   963
AGN BROADLINE               336
STARFORMING BROADLINE       188
STARBURST BROADLINE          23
Name: count, dtype: int64

# Bin 03 New

## Data

In [20]:
bin_id = 'bin_03'
idx_id_bin_03 = np.load(
    f"{data_dir}/202511_bins/"
    f"{bin_id}/{bin_id}_index_specobjid.npy"
)

bin_03_new_df = drop_meta_data_df.loc[idx_id_bin_03[:, 1]].copy()

## z and S/N

In [21]:
bin_03_new_df[['z', 'snMedian']].describe()

                   z       snMedian
count  182033.000000  182033.000000
mean        0.080163      24.228334
std         0.037077       6.742897
min         0.010013      17.548260
25%         0.052647      19.390560
50%         0.076403      22.085040
75%         0.103458      26.856050
max         0.294866      96.935780

## SDSS class

In [22]:
bin_03_new_class = bin_03_new_df.subClass.value_counts(dropna=False)
bin_03_new_class

subClass
NaN                      116778
STARFORMING               38436
STARBURST                 10220
BROADLINE                  8244
AGN                        6473
AGN BROADLINE              1257
STARFORMING BROADLINE       606
STARBURST BROADLINE          19
Name: count, dtype: int64

# Class accross bins

In [26]:
all_bins_classes = [bin_00_class, bin_01_class, bin_02_class, bin_03_new_class]

classes_df = pd.concat(
    all_bins_classes, 
    axis=1, 
    keys=['bin0', 'bin1', 'bin2', 'bin3']
)
classes_df.to_clipboard()
classes_df

                        bin0    bin1    bin2    bin3
subClass
NaN                    88672  104200  113403  116778
STARFORMING            73255   60906   50770   38436
STARBURST              18155   13200   12267   10220
AGN                     1647    2962    4083    6473
BROADLINE                134     395     963    8244
AGN BROADLINE             87     214     336    1257
STARFORMING BROADLINE     62     134     188     606
STARBURST BROADLINE       21      22      23      19

# Bin 03

## Data

In [24]:
idx_id_bin_03 = np.load(
    f"{data_dir}/{bin_id}/{bin_id}_index_specobjid.npy"
)
bin_03_df = drop_meta_data_df.loc[idx_id_bin_03[:, 1]].copy()

## z and S/N

In [27]:
bin_03_df[['z', 'snMedian']].describe()

                   z       snMedian
count  181850.000000  181850.000000
mean        0.080209      24.209400
std         0.037052       6.719912
min         0.010013      17.543710
25%         0.052717      19.383460
50%         0.076443      22.073380
75%         0.103513      26.834085
max         0.294866      92.638030

## SDSS class

In [28]:
bin_03_df.subClass.value_counts(dropna=False)

subClass
NaN                      116821
STARFORMING               38464
STARBURST                 10050
BROADLINE                  8203
AGN                        6444
AGN BROADLINE              1249
STARFORMING BROADLINE       604
STARBURST BROADLINE          15
Name: count, dtype: int64